version: '3'
services:
  adguard-home:
    image: adguard/adguardhome
    container_name: Adguard-Home
    restart: always
    networks:
      - internal
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - '84:80/tcp' #webport
      - '53:53/udp' #DNS
      - '53:53/tcp' #DNS
      - '853:853/tcp'
      - '3333:3000/tcp'
    volumes:
      - './opt:/opt/adguardhome/work'
      - './confdir:/opt/adguardhome/conf'
volumes:
 adguardvolume:
