version: '3.5'
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SERVER_HTTP_PORT=3005
    ports:
      - 3005:3005
    deploy:
      replicas: 1
  influxdb:
    image: influxdb:1.8.10
    restart: always
    ports:
      - 8086:8086 #expose data on port 8086
      - 25826:25826 #read data from collectd source on port 25826
    volumes:
      - ./influxdbvolume:/var/lib/influxdb2
      - ./docker/influxdb/types.db:/usr/share/collectd/types.db:ro
        #- ./docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        #influxdb.conf causes a problem with types.db need to understand how to configure influxdb.conf
    deploy:
      replicas: 0
      


 # loki:
    #image: grafana/loki:2.4.1
   # container_name: loki
   # restart: always
    #ports:
   #   - 3100:3100
    #expose:
   #   - 3100
   # command: -config.file=/etc/loki/local-config.yaml
    #networks:
     # - internal
 #   deploy:
   #   replicas: 0

      
      
      #Optional
        #https://github.com/grafana/loki/issues/974
        #If on x86_64, to mirror docker logs to grafana - loki data source
        #loki-docker-driver:
        #image: grafana/loki-docker-driver:main-28d845d
        #restart: always
        #deploy:
        #replicas: 1
