services:
  adguard:
    image: adguard/adguardhome:latest
    ports:
      - 53:53 #DNS
      - 67:67 #DHCP Server
      - 3009:3000 #webport
      - 853:853 #DNS over TLS
      - 5443:5443 #DNSCRYPT
    volumes:
      - ./adguard/workdir:/opt/adguardhome/work
      - ./adguard/confdif:/opt/adguardhome/conf
