version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    ports:
      - 5353:5353/tcp
      - 5353:5353/udp
      - 3000:3000/tcp
      - 8080:8080/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
    deploy:
      replicas: 1
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SERVER_HTTP_PORT=3005
    ports:
      - 3005:3005
    deploy:
      replicas: 0
      
  #influx i think is for another non adguard related service    
  influxdb:
    image: influxdb:1.8.10
    restart: always
    ports:
      - 8086:8086 #expose data on port 8086
      - 25826:25826 #read data from collectd source on port 25826
    volumes:
      - ./influxdbvolume:/var/lib/influxdb2
      - ./docker/influxdb/types.db:/usr/share/collectd/types.db:ro
        #- ./docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        #influxdb.conf causes a problem with types.db need to understand how to configure influxdb.conf
    deploy:
      replicas: 0
