reporting-disabled = false
#bind-address = "127.0.0.1:8088"

[meta]
  dir = "/var/lib/influxdb/meta"
  #retention-autocreate = true
  #logging-enabled = true

[data]
  dir = "/var/lib/influxdb/data"
  #index-version = "inmem"
  wal-dir = "/var/lib/influxdb/wal"
  #wal-fsync-delay = "0s"
  #validate-keys = false
  #strict-error-handling = false
  #query-log-enabled = true
  #cache-max-memory-size = 1073741824
  #cache-snapshot-memory-size = 26214400
  #cache-snapshot-write-cold-duration = "10m0s"
  #compact-full-write-cold-duration = "4h0m0s"
  #compact-throughput = 50331648
  #compact-throughput-burst = 50331648
  #max-series-per-database = 1000000
  #max-values-per-tag = 100000
  #max-concurrent-compactions = 0
  #max-index-log-file-size = 1048576
  #series-id-set-cache-size = 100
  #series-file-max-concurrent-snapshot-compactions = 0
  #trace-logging-enabled = false
  #tsm-use-madv-willneed = false

[[collectd]]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
  typesdb = "/usr/share/collectd/types.db"
  security-level = "none"
  auth-file = "/etc/collectd/auth_file"
  parse-multivalue-plugin = "split"
